### ISSUE TITLE
[Template] add template engine for Yaml file , to help parametric configuration. First shared in one application some env/port settings

### ISSUE THREAD

**Issue by franckOL** [franckOL/Controller#1]
The first version has only a `self` object to help configuration, and it refere to the document itself.
The template engine `liquidjs` is use for all `POST`, `PUT` verbs for all API routes.

The purpose is to do something like that in yaml file (so json equivalent also):
```yaml

---
apiVersion: iofog.org/v2
kind: Application
metadata:
  name: edai-smartbuilding-rules-engine
spec:
  microservices:
    - name: rulesengine
      agent:
        name: agent-aismall01
        config: {} 
      images:
        x86: nodered/node-red:latest
        arm: nodered/node-red:latest
        registry: remote
      config: {} 
      container:
        rootHostAccess: false 
        volumes: [] 
        ports:
          - internal: 1880
            external: 1880
        env:  
          - key: selfname
            value: "{{ self.name }}"
          - key: http_proxy
            value: "http://proxy.rd.francetelecom.fr:8080/"
          - key: https_proxy
            value: "{{ self.microservices | where: \"name\", \"rulesengine\" | first | map: \"env\" | first | where: \"key\" , \"http_proxy\" | first | map: \"value\" | first }}"
    - name: service2
      agent:
        name: agent-aismall02
        config: {} 
      images:
        x86: xx/service2:latest
        arm: xx/service2:latest
        registry: remote
      config: {} 
      container:
        rootHostAccess: false 
        volumes: [] 
        ports:
          - internal: 1881
            external: 1882
        env:  
          - key: selfname
            value: "{{ self.name }}"
          - key: http_proxy
            value: "{{ self.microservices | where: \"name\", \"rulesengine\" | first | map: \"env\" | first | where: \"key\" , \"http_proxy\" | first | map: \"value\" | first }}"
          - key: https_proxy
            value: "{{ self.microservices | where: \"name\", \"rulesengine\" | first | map: \"env\" | first | where: \"key\" , \"http_proxy\" | first | map: \"value\" | first }}"
          - key: rulesengineHOST
            value: "Need agent context"
          - key: rulesenginePORT
            value: "{{ self.microservices | where: \"name\", \"rulesengine\" | first | map: \"ports\" | first| first |map: \"external\" | first }}"
```

Next improvements:
 - [ ] only apply on precise route: routes use by agent don't need that
 - [ ] Add all controller applications to context of template rendering (lazy loading)
 - [ ] Add all controller edge ressources to context of template rendering (lazy loading)
 - [ ] Add all controller agent to context of template rendering (lazy loading)
